# Docker Compose Configuration

# Docker Compose is a tool that allows you to define and run multi-container Docker applications.
# It uses a YAML file to configure the services, networks, and volumes required for an application.

version: "3.9"

# Docker Compose configuration for the Django backend service
services:
  app:
    depends_on:
      - db
    db:
      image: postgres:13-alpine
    # build from current directory
    build:
      context: .
      args:
        - DEV=true
    # maps 8000 on the machine, to 8000 on the docker container
    ports:
      - "8000:8000"
    # map system dir into docker container, updates in local code will be reflected in running container in real time
    volumes:
      - ./app:/app
    # command that runs the service is run by default if not overridden in dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    