---

name: Checks # name as appears in github actions

on: [push] # run on action

jobs:
  # env:
  #     CHATGPT_API_TOKEN: ${{ secrets.CHATGPT_API_TOKEN }}
  test-lint:
    name: Test and lint # human friendly name you'll see in github actions interface
    runs-on: ubuntu-20.04 # operating system the job will run on (basic linux)
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout 
        uses: actions/checkout@v2 # action provided by github which checks the code out
      - name: Test app
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

